spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@dispatchflowdb_high}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

oracle.wallet.location=${TNS_ADMIN:./Wallet_DISPATCHFLOWDB}

dispatch.storage.s3.enabled=true
aws.s3.bucket-name=${S3_BUCKET_NAME:dispatch-flow-prod}
aws.s3.region=${AWS_REGION:us-east-1}

efs.base-path=${EFS_BASE_PATH:/app/efs}

# ==========================================
# SEGURIDAD - AZURE AD B2C (IDaaS)
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_B2C_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_B2C_JWK_SET_URI}

# (Opcional) Para depurar si el token es rechazado en el servidor EC2
logging.level.org.springframework.security=INFO