spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@dispatchflowdb_high}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

oracle.wallet.location=${TNS_ADMIN:./Wallet_DISPATCHFLOWDB}

dispatch.storage.s3.enabled=true
aws.s3.bucket-name=dispatch-flow-prod
aws.s3.region=${AWS_REGION:us-east-1}
